# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#Pipeline Name
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none
variables:
  -name: TFPath
    value:'terraform'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Lint
    displayName: 'Linting and Readiness Check'
    jobs:
      - job: Validate
        displayName: "Terraform Validate"
        steps:
        - script: |
            terraform vlaidate -check-variables=false
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
          displayName: 'Terraform Validate'
          
      
  - stage: Build
    jobs:
      - job: JobOne
        steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'
          - task: CopyFiles@2
            displayName: "Copy Terraform Files"
            inputs:
              SourceFolder: 'terraform'
              Contents: '**'
              TargetFolder: '$(build.artifactstagingdirectory)/drop-terraform'
              
  - stage: deploy
    jobs:
      - job: JobTwo
        steps:  
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              Write-Host "Hello World"
